### PR TITLE
Search date scroll

### PR DESCRIPTION
**Pull request by poornima-alugubelly**
- Added search feature
- Removed console and unnecessary code
- Formatted posted time similar to twitter's
- Added circular progress for tweet

### CODE REVIEW

**Review by gopalbbharadva — APPROVED** [review]
Everything looks fine, Features working fine. 
Bug: If i type blank spaces in post it allows me to post. you can solve it by trim() ig.

**Comment by poornima-alugubelly** [comment]
> Everything looks fine, Features working fine. Bug: If i type blank spaces in post it allows me to post. you can solve it by trim() ig.

Fixed it thank u!

**Review by talrejah02 — APPROVED** [review]
Great work, nice folder structure
review: search result are still displayed aften when i click on any search result.

**Comment by poornima-alugubelly** [comment]
> Great work, nice folder structure review: search result are still displayed aften when i click on any search result.

Fixed it thank u for checking! : )

**Pull request merged**
